<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('AdsBoard')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/admin.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
</head>
<body>
<div class="container-fluid nopadding">
    <nav class="navbar navbar-default" id="main-navbar">
        <div class="container-fluid">

            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">AdsBoard</a>
            </div>

            <div class="container collapse navbar-collapse">

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?php echo $this->url('registration'); ?>">Сообщения</a></li>
                    <li><a href="<?php echo $this->url('logout'); ?>">Выход</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Нет</button>
                <button type="button" class="btn btn-primary delete">Да</button>
            </div>
        </div>
    </div>
</div>

<div id="content" class="container-fluid nopadding">
    <div id="left-menu" class="col-md-3 nopadding">
        <ul class="nav nav-stacked">
            <li><a class="left-admin-menu" href="#">Главная</a></li>
            <hr>
            <li><a class="left-admin-menu" href="<?= $this->url('showCategories') ?>">Категории</a></li>
            <hr>
            <li><a class="left-admin-menu" href="<?= $this->url('showUsers') ?>">Пользователи</a></li>
        </ul>
    </div>
    <div id="plugins" class="col-md-9">
        <?php echo $this->content; ?>
    </div>
</div>

<script>
    $('#left-menu').height($(document).height() - $('#main-navbar').height() - 3);
    $('#plugins').height($(document).height() - $('#main-navbar').height() - 3);

    $(document).ajaxComplete(function (event, request) {
        if (/^3\d{2}$/.test(request.status)) {
            window.location.href = request.getResponseHeader('Location');
        }
    });
</script>

</body>
</html>
