<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('AdsBoard')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/admin.css')
        ->prependStylesheet($this->basePath() . '/css/reset.min.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/common/ajax-redirect.js')
        ->prependFile($this->basePath() . '/js/bootstrap-notify/bootstrap-notify.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
</head>
<body>
<div class="container-full">
    <nav class="navbar navbar-default" id="main-navbar">
        <div class="row-fluid">

            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">AdsBoard</a>
            </div>

            <div class="container collapse navbar-collapse">

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?php echo $this->url('registration'); ?>">Сообщения</a></li>
                    <li><a href="<?php echo $this->url('logout'); ?>">Выход</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="row">
        <div id="left-menu" class="col-md-3">
            <ul class="nav nav-stacked left-admin-menu">
                <li><a href="#">Главная</a></li>
                <hr>
                <li><a href="<?= $this->url('showCategories') ?>">Категории</a></li>
                <hr>
                <li><a href="<?= $this->url('showUsers') ?>">Пользователи</a></li>
                <hr>
                <li><a href="<?= $this->url('adminMessages') ?>">Сообщения</a></li>
            </ul>
        </div>
        <div id="plugins" class="col-md-9">
            <?php echo $this->content; ?>
        </div>
    </div>
</div>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Нет</button>
                <button type="button" class="btn btn-primary delete">Да</button>
            </div>
        </div>
    </div>
</div>

<?php echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/common/admin/admin.js'); ?>
</body>
</html>
