<?php $this->inlineScript()
    ->appendFile($this->basePath() . 'js/common/base/show-form-ads.js')
    ->appendFile($this->basePath() . 'js/form-builder/form-field.js')
    ->appendFile($this->basePath() . 'js/jquery-img-upload/jquery-img-upload.js')
    ->appendFile($this->basePath() . 'js/jquery-form/jquery-form.js') ?>

<?php $this->headLink()
    ->prependStylesheet($this->basePath() . 'css/jquery-img-upload/jquery-img-upload.css') ?>

<div class="container-fluid">
    <div class="row">
        <div class="page-header">
            <h3>Подать объявление</h3>
        </div>
    </div>
    <div class="row">
        <form id="ads-create" action="<?php echo $this->url('createAds');?>" class="form-horizontal" method="post"
              enctype="multipart/form-data">
            <?php echo $this->formFileSessionProgress(); ?>
            <div class="row">
                <div class="col-lg-6 col-lg-push-3">
                    <div class="form-group required">
                        <label class="control-label">Имя</label>
                        <input type="text" class="form-control" name="userName" placeholder="Ввведите имя">
                        <span class="help-block"></span>
                    </div>
                    <div class="form-group required">
                        <label class="control-label">Телефон</label>

                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">+38</span>
                            <input type="text" class="form-control" name="telephone" placeholder="Ввведите телефон">
                        </div>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-lg-push-3">
                    <div class="form-group">
                        <label class="control-label">Область</label>
                        <select id="region" data-url="<?php echo $this->url('getRegions');?>" name="region" class="form-control selectpicker">
                            <option value="" selected disabled>Вся Украина</option>
                            <?php foreach ($regions as $region): ?>
                                <option value="<?= $region['id'] ?>"><?= $region['name'] ?></option>
                            <?php endforeach ?>
                        </select>
                        <span class="help-block"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Город</label>
                        <select id="city" data-url="<?php echo $this->url('getCities');?>" name="city" class="form-control selectpicker">
                            <option value="" selected disabled>Все города</option>
                        </select>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-lg-push-3">
                    <div class="form-group required">
                        <label class="control-label">Категория</label>
                        <select id="main-category" data-url="<?php echo $this->url('getCategories');?>" name="category[0]" class="form-control selectpicker">
                            <option value="0" selected>-- Выберете категорию --</option>
                            <?php foreach ($cats as $cat): ?>
                                <option value="<?= $cat['id'] ?>"><?= $cat['name'] ?></option>
                            <?php endforeach ?>
                        </select>
                        <span class="help-block"></span>
                    </div>
                    <div class="form-group hide required">
                        <label class="control-label">Подкатегория</label>
                        <select class="form-control selectpicker subcategory">
                            <option value="0" selected>-- Выберете подкатегорию --</option>
                        </select>
                        <span class="help-block"></span>
                    </div>
                    <div id="attributes" class="form-group hide">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-lg-push-3">
                    <div class="form-group required">
                        <label class="control-label">Заголовок</label>
                        <input type="text" class="form-control" name="title" placeholder="Ввведите заголовок">
                        <span class="help-block"></span>
                    </div>
                    <div class="form-group required">
                        <label class="control-label">Описание</label>
                    <textarea rows="10" cols="20" class="form-control" name="description"
                              placeholder="Описание товара"></textarea>
                        <span class="help-block"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Цена</label>

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="input-group">
                                    <input type="number" class="form-control" name="price" value=""
                                           placeholder="Ввведите цену">
                                <span class="input-group-btn">
                                    <select class="btn btn-default selectpicker" name="currency">
                                        <?php foreach ($currencies as $currency): ?>
                                            <option value="<?= $currency['id'] ?>"><?= $currency['name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </span>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="checkbox">
                                    <label>
                                        <input id="no-price" type="checkbox" name="no-price" value="no-price">
                                        Договорная
                                    </label>
                                </div>
                            </div>
                        </div>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-lg-push-3">
                    <div class="form-group jFilter">
                        <label class="control-label">Фото</label>
                        <a class="btn btn-default file_input" data-jfiler-name="files"
                           data-jfiler-extensions="jpg, jpeg, png, gif"><i class="icon-jfi-paperclip"></i> Выбрать
                            изображение</a>
                        <span class="help-block"></span>
                    </div>
                    <div id="progress" class="row progress hide">
                        <div class="progress-bar progress-bar-striped active" role="progressbar">
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <button type="submit" class="btn btn-default">Опубликовать</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
