<div class="container">
    <div class="row row-buffer">
        <div class="col-lg-4 col-lg-push-4">
            <?php if (!empty($error)): ?>
                <div class="alert alert-danger" role="alert"><?= $error ?></div>
            <?php endif; ?>
            <form action="<?= $this->url('login') ?>" method="post">
                <div class="form-group">
                    <label for="InputEmail1">Введите email</label>
                    <input type="email" name="email" class="form-control" id="InputEmail1"
                           value="<?= $form->get('email')->getValue(); ?>">
                </div>
                <div class="form-group">
                    <label for="InputPassword1">Введите пароль</label>
                    <input type="password" name="password" class="form-control" id="InputPassword1">
                </div>
                <div class="form-group text-right">
                    <button type="submit" class="btn btn-default">Войти</button>
                </div>
            </form>
        </div>
    </div>
</div>