<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/checkbox-x.min.js') ?>
<?php echo $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/checkbox-x.min.css') ?>

<?php if (!empty($this->categories)): ?>
    <?= $this->partial('ads/partial/left-menu/search-category') ?>
<?php elseif (!empty($this->attributes)): ?>
    <?= $this->partial('ads/partial/left-menu/attributes') ?>
<?php endif; ?>

<?= $this->partial('ads/partial/left-menu/search-location') ?>
