<?php
$url = $this->url(
    'search',
    array(),
    array(
        'query' => $this->search
    )
);
?>

<form action="<?= $this->url('search') ?>">
    <?php if (!empty($this->search)): ?>
        <?php foreach ($this->search as $key => $val): ?>
            <?php if ($key !== 'regionId' && $key !== 'cityId'): ?>
                <input type="hidden" name="<?= $key ?>" value="<?= $val ?>">
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <div class="row margin-top55">
        <div class="col-lg-12">
            <div class="form-group">
                <label class="control-label">Область</label>
                <select id="region" name="regionId" class="form-control input-sm">
                    <?php if (!empty($this->search['regionId'])): ?>
                        <option value="<?= $this->search['regionId'] ?>" selected>Вся Украина</option>
                    <?php else: ?>
                        <option value="" selected>Вся Украина</option>
                    <?php endif; ?>
                </select>
                <span class="help-block"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Город</label>
                <select id="city" name="cityId" class="form-control input-sm">
                    <?php if (!empty($this->search['cityId'])): ?>
                        <option value="<?= $this->search['cityId'] ?>" selected>Вся область</option>
                    <?php else: ?>
                        <option value="" selected>Вся область</option>
                    <?php endif; ?>
                </select>
                <span class="help-block"></span>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="form-group text-right">
                <button type="submit" class="btn btn-default btn-sm">Поиск</button>
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $('#region').change(function () {
            var target = $(this);
            $.ajax({
                type: 'POST',
                url: '/getCities',
                dataType: 'json',
                data: {regionid: target.val()},
                success: function (data) {
                    var $city = $('#city');

                    $city.find("option[value!='']").remove();

                    $.each(data['cities'], function (index, value) {
                        $('#city').append(
                            $('<option>')
                                .attr('value', value['id'])
                                .text(value['name']))
                    });
                },
                error: function (xhr) {
                    alert(xhr.status + ' ' + xhr.responseText)
                }
            });
        });

        $.ajax({
            url: '/getRegions',
            dataType: 'json',
            success: function (data) {
                var $region = $('#region');

                $.each(data['regions'], function (index, value) {
                    $region.append(
                        $('<option>')
                            .attr('value', value['id'])
                            .text(value['name']))
                });
            },
            error: function (xhr) {
                alert(xhr.status + ' ' + xhr.responseText)
            }
        });
    });
</script>