<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.6.0/bootstrap-table.min.css">

<table data-toggle="table"
       data-url="http://mikepenz.com/jsfiddle/"
       data-pagination="true"
       data-side-pagination="server"
       data-page-list="[5, 10, 20, 50, 100, 200]"
       data-search="true"
    >
    <thead>
    <tr>
        <th class="col-lg-1" data-field="state">id</th>
        <th class="col-lg-3" data-field="id" data-align="left" data-sortable="true">Email</th>
        <th class="col-lg-2" data-field="name" data-align="left" data-sortable="true">Объявления</th>
        <th class="col-lg-2" data-field="name" data-align="left" data-sortable="true">Аккаунт</th>
        <th class="col-lg-2" data-field="price" data-align="left" data-sortable="true">Статус</th>
    </tr>
    </thead>
</table>

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.6.0/bootstrap-table.min.js"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.6.0/locale/bootstrap-table-ru-RU.min.js"></script>