<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('AdsBoard')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/animate/animate.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
        ->prependStylesheet($this->basePath() . '/css/drop-down-submenu/drop-down-submenu.css')
        ->prependStylesheet($this->basePath() . '/css/header/header.css')
        ->prependStylesheet($this->basePath() . '/css/footer/footer.css')
        ->prependStylesheet($this->basePath() . '/css/reset.min.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/common/ajax-redirect.js')
        ->prependFile($this->basePath() . '/js/common/app-layout.js')
        ->prependFile($this->basePath() . '/js/bootstrap-notify/bootstrap-notify.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>

<div class="container">
    <nav class="navbar navbar-default" id="main-navbar">
        <div class="container-fluid">

            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">AdsBoard</a>
            </div>

            <div class="container collapse navbar-collapse">
                <form class="navbar-form navbar-left" action="<?= $this->url('search') ?>" role="search">
                    <div class="form-group">
                        <div class="dropdown">
                            <?php if (!empty($this->region)): ?>
                                <input id="location" type="hidden" name="regionId"
                                       value="<?= $this->region->getId() ?>">
                                <a id="selected-location" role="button" data-toggle="dropdown"
                                   class="btn btn-default dropdown-toggle">
                                    <span class="selected"><?= $this->region->getName() ?></span>
                                    <span class="caret"></span>
                                </a>
                            <?php elseif (!empty($this->city)): ?>
                                <input id="location" type="hidden" name="cityId" value="<?= $this->city->getId() ?>">
                                <a id="selected-location" role="button" data-toggle="dropdown"
                                   class="btn btn-default dropdown-toggle">
                                    <span class="selected"><?= $this->city->getName() ?></span>
                                    <span class="caret"></span>
                                </a>
                            <?php else: ?>
                                <input id="location" type="hidden" name="" value="">
                                <a id="selected-location" role="button" data-toggle="dropdown"
                                   class="btn btn-default dropdown-toggle">
                                    <span class="selected">Вся Украина </span>
                                    <span class="caret"></span>
                                </a>
                            <?php endif; ?>
                            <ul id="locationList"
                                data-url-cities="<?php echo $this->url('getCities');?>"
                                data-url-regions="<?php echo $this->url('getRegions');?>"
                                class="dropdown-menu multi-level"
                                role="menu"
                                aria-labelledby="dropdownMenu">
                                <li><a href="#">Вся Украина</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="text" name="query"
                               class="form-control"
                               size="40"
                               placeholder="Ввведите, то что ищите"
                               value="<?= !empty($this->query) ? $this->query : '' ?>">
                    </div>
                    <div class="form-group">
                        <div class="dropdown">
                            <?php if (!empty($this->category)): ?>
                                <input id="categoryId" type="hidden" name="categoryId"
                                       value="<?= $this->category->getId() ?>">
                                <a id="selected-category" role="button" data-toggle="dropdown"
                                   class="btn btn-default dropdown-toggle">
                                    <span class="selected"><?= $this->category->getName() ?></span>
                                    <span class="caret"></span>
                                </a>
                            <?php else: ?>
                                <input id="categoryId" type="hidden" name="" value="">
                                <a id="selected-category" role="button" data-toggle="dropdown"
                                   class="btn btn-default dropdown-toggle">
                                    <span class="selected">Все категории</span>
                                    <span class="caret"></span>
                                </a>
                            <?php endif; ?>
                            <ul id="categories"
                                data-url="<?php echo $this->url('getCategories');?>"
                                data-url-root="<?php echo $this->url('getRootCategories');?>"
                                class="dropdown-menu multi-level"
                                role="menu"
                                aria-labelledby="dropdownMenu">
                                <li><a href="#">Все категории</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Поиск</button>
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <?php if ($user = $this->identity()) { ?>
                        <li>
                            <a href="<?php echo $this->url('getUserAds'); ?>">Ваши объявления</a>
                        </li>
                        <li><a href="<?php echo $this->url('logout'); ?>">Выход</a></li>
                    <?php } else { ?>
                        <li><a href="<?php echo $this->url('registration'); ?>">Регистрация</a></li>
                        <li><a href="<?php echo $this->url('login'); ?>">Вход</a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="container">
    <?php echo $this->content; ?>
</div>


<div class="footer">
    <div class="container">
        <p>&copy; <?php echo date('Y') ?> by MaxTech</p>
    </div>
</div>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default modal-no" data-dismiss="modal">Нет</button>
                <button type="button" class="btn btn-primary modal-yes">Да</button>
            </div>
        </div>
    </div>
</div>

<?php echo $this->inlineScript(); ?>
</body>
</html>
