<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/bootstrap-table/bootstrap-table.min.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap-table/bootstrap-editable.css'); ?>


<?php $this->inlineScript()
    ->appendFile($this->basePath() . '/js/bootstrap-table/bootstrap-table.js')
    ->appendFile($this->basePath() . '/js/bootstrap-table/locale/bootstrap-table-ru-RU.min.js')
    ->appendFile($this->basePath() . '/js/bootstrap-table/bootstrap-editable.min.js')
    ->appendFile($this->basePath() . '/js/common/admin/users.js'); ?>

<table data-toggle="table"
       data-url="<?= $this->url('getUsers') ?>"
       data-pagination="true"
       data-side-pagination="server"
       data-page-list="[5, 10, 20, 50, 100, 200]"
       data-search="true"
    >
    <thead>
    <tr>
        <th class="col-lg-1" data-field="id" data-align="left" data-sortable="true">id</th>
        <th class="col-lg-5" data-field="email" data-align="left" data-sortable="true">Email</th>
        <th class="col-lg-2" data-field="ads" data-align="left" data-sortable="true" data-events="adsEvents">
            Объявления
        </th>
        <th class="col-lg-2" data-field="role" data-align="left" data-sortable="true" data-editable="true">Роль</th>
        <th class="col-lg-2" data-field="stat" data-align="left" data-sortable="true" data-editable="true">Статус
        </th>
    </tr>
    </thead>
</table>

<div id="ads-preview-block">
    <div id="back"><a href="#" class="btn btn-link btn-lg">&lt; Назад</a></div>

    <div class="panel-group" id="ads-preview">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#ads-preview" href="#collapseOne">
                    </a><i class="indicator glyphicon glyphicon-chevron-down  pull-right"></i>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
                <div class="panel-body">
                </div>
            </div>
        </div>
    </div>
</div>