<?php $this->inlineScript()
    ->appendFile($this->basePath() . '/js/bootstrap-table/bootstrap-gtreetable.js')
    ->appendFile($this->basePath() . '/js/common/admin/category.js'); ?>

<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/bootstrap-table/bootstrap-gtreetable.css'); ?>

<div id="edit-form-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <?php echo $this->partial('form-builder') ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button id="save-form" type="button" class="btn btn-primary" data-dismiss="modal">Сохранить</button>
            </div>
        </div>
    </div>
</div>

<table class="table gtreetable" id="gtreetable">
    <thead>
    <tr>
        <th><h3 class="col-lg-6 nopadding">Категории объявлений</h3>

            <div class="col-lg-6 text-right nopadding">
                <button id="add-root" class="btn btn-lg btn-default">Добавить корневую категорию</button>
            </div>
        </th>
    </tr>
    </thead>
</table>