<?php echo $this->headScript()
    ->appendFile($this->basePath() . '/js/bootstrap-gtreetable.js'); ?>
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-gtreetable.css')
?>
<div id="edit-form-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <?php echo $this->partial('form-builder') ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button id="save-form" type="button" class="btn btn-primary" data-dismiss="modal">Сохранить</button>
            </div>
        </div>
    </div>
</div>

<table class="table gtreetable" id="gtreetable">
    <thead>
    <tr>
        <th><h3 class="col-lg-6 nopadding">Категории объявлений</h3>

            <div class="col-lg-6 text-right nopadding">
                <button id="add-root" class="btn btn-lg btn-default">Добавить корневую категорию</button>
            </div>
        </th>
    </tr>
    </thead>
</table>


<script>


    jQuery('#gtreetable').gtreetable({
        'source': function (id) {
            return {
                type: 'POST',
                url: '/admin/categories',
                data: {'id': id},
                dataType: 'json',
                error: function (XMLHttpRequest) {
                    alert(XMLHttpRequest.status + ': ' + XMLHttpRequest.responseText);
                }
            }
        },
        'onSave': function (oNode) {
            return {
                type: 'POST',
                url: '/admin/categories/' + (!oNode.isSaved() ? 'add' : 'update'),
                data: {
                    name: oNode.getName(),
                    id: (!oNode.isSaved() ? oNode.getParent() : oNode.getId())
                },
                dataType: 'json',
                error: function (XMLHttpRequest) {
                    alert(XMLHttpRequest.status + ': ' + XMLHttpRequest.responseText);
                }
            };
        },
        'onDelete': function (oNode) {
            return {
                type: 'POST',
                url: '/admin/categories/delete',
                data: {
                    id: oNode.getId()
                },
                dataType: 'json',
                error: function (XMLHttpRequest) {
                    alert(XMLHttpRequest.status + ': ' + XMLHttpRequest.responseText);
                }
            };
        },
        "selectLimit": 0,
        "manyroots": true,
        "language": "ru-RU",
        "inputWidth": "200px"
    });

    $('#add-root').click(function () {
        $('tr.node .node-action-0').eq(0).trigger('click');
    })

</script>