<?= $this->partial('application/index/index.phtml') ?>
<div class="row">
    <div class="col-lg-3 nopadding-rgt">
        <?= $this->partial('ads/partial/left-menu') ?>
    </div>
    <div class="col-lg-9 nopadding-lft">
        <?= $this->partial('ads/partial/ads-block') ?>
        <div class="paginator">
            <?= $this->partial('ads/partial/paginator') ?>
        </div>
    </div>
</div>
