<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Категории Объявлений</h3>
            </div>
            <ul class="list-group">
                <li class="list-group-item">Cras justo odio</li>
                <li class="list-group-item">Dapibus ac facilisis in</li>
                <li class="list-group-item">Morbi leo risus</li>
                <li class="list-group-item">Porta ac consectetur ac</li>
                <li class="list-group-item">Vestibulum at eros</li>
            </ul>
        </div>
    </div>

    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Последние Объявления</h3>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="media">
                        <div class="media-left media-middle">
                            <a href="#">
                                <img class="media-object pull-left" src="<?= $this->basePath() . 'cyber%20(5).png' ?>"
                                     alt="..." width="50px" height="50px">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">Middle aligned media</h4>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
