<?= $this->partial('application/index/index.phtml') ?>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Категории Объявлений</h3>
            </div>
            <ul class="list-group">
                <?php foreach ($this->adsMenu['data'] as $cat): ?>
                    <li class="list-group-item">
                        <a href="<?= $this->url('adsByCategory', array('catId' => $cat['id'])) ?>">
                            <?= $this->escapeHtml($cat['name']) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="col-lg-9">
        <?= $this->partial('ads/partial/ads-block.phtml') ?>
        <div class="paginator">
            <?= $this->partial('ads/partial/paginator.phtml') ?>
        </div>
    </div>
</div>