<?php $this->headScript()
    ->appendFile($this->basePath() . '/js/common/base/show-ads.js')
    ->appendFile($this->basePath() . '/js/image-gallery/jquery.blueimp-gallery.min.js')
    ->appendFile($this->basePath() . '/js/image-gallery/bootstrap-image-gallery.js')
    ->appendFile($this->basePath() . '/js/validator/validator.min.js')
?>
<?php $this->headLink()
    ->appendStylesheet($this->basePath() . '/css/image-gallery/bootstrap-image-gallery.min.css')
    ->appendStylesheet($this->basePath() . '/css/image-gallery/blueimp-gallery.min.css')
    ->appendStylesheet($this->basePath() . '/css/ads-view.css')
?>

<div class="row">
    <div class="col-lg-12 ">
        <h3><?= $ads->getTitle() ?></h3>
    </div>
</div>
<div class="ads row margin-top25">
    <div class="col-lg-4 border-right">
        <div>
            <h2>
                <?php if (!empty($ads->getPrice())): ?>
                    <?= $this->escapeHtml($ads->getPrice()) ?>
                    <?= $ads->getCurrencyid()->getName() ?>
                <?php else: ?>
                    Договорная
                <?php endif; ?>
            </h2>
        </div>
        <div class="margin-bottom40">
            <div class="margin-bottom40">
                <h5>
                    <a href="<?= $this->url('adsByCategory',
                        array('catId' => $ads->getCategoryid()->getId())) ?>">
                        <?= $ads->getCategoryid()->getName() ?>
                    </a>
                </h5>
                <h5>
                    Область: <?= !empty($ads->getRegionid())?$ads->getRegionid()->getName():'Вся Украина'; ?>
                    Город: <?= !empty($ads->getCityid())?$ads->getCityid()->getName():'Все города'; ?>
                </h5>
            </div>
            <h3 class="border-bottom">
                <?= $this->escapeHtml($ads->getUserName()) ?>
            </h3>
            <h4>
                Телефон: +38<?= $this->escapeHtml($ads->getTelephone()) ?>
            </h4>
        </div>
        <div class="published">
            <h4>
                Опубликовано: <?= $ads->getCreated()->format('Y-m-d') ?>
            </h4>
        </div>
        <div class="complain">
            <a href="#">
                Пожаловаться на объявление
            </a>
        </div>
    </div>
    <div class="col-lg-8">
        <?php $images = glob("./public/img/ads_imgs/{$ads->getId()}_*"); ?>
        <?php if (!empty($images)): ?>
            <div id="links" class="border-bottom">
                <?php foreach (glob("./public/img/ads_imgs/{$ads->getId()}_*") as $filename): ?>
                    <a href="/img/ads_imgs/<?= basename($filename) ?>" data-gallery>
                        <img src="<?php echo $this->thumbHelper(basename($filename)); ?>"
                             alt="..." width="170" height="170">
                    </a>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <?php if (!empty($this->props)): ?>
            <div id="props" class="border-bottom">
                <ul class="unstyled">
                    <?php foreach ($this->props as $key => $vals): ?>
                        <li>
                            <?= $key ?>:
                            <?= implode(', ', $vals) ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <div class="ads-description">
            <?= nl2br($this->escapeHtml($ads->getDescription())) ?>
        </div>
    </div>
</div>

<div id="blueimp-gallery" class="blueimp-gallery">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Пожаловаться на объявление</h4>
            </div>
            <div class="modal-body">
                <form action="<?php echo $this->url('sendComplainMessage',array('adsId' => $ads->getId()));?>" id="complain" data-toggle="validator" data-notify-success="Сообщение успешно отправлено">
                    <div class="form-group">
                        <label for="inputEmail" class="control-label">Email</label>
                        <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email" data-error="Не правильный email" required>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group">
                        <label for="inputTwitter" class="control-label">Сообщение</label>
                        <textarea name="message"
                                  data-minlength="20"
                                  data-minlength-error="Слишком короткое сообщение"
                                  data-maxlength="100"
                                  data-maxlength-error="Слишком длинное сообщение"
                                  class="form-control"
                                  rows="8" required></textarea>
                        <div class="help-block with-errors"></div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="button" class="btn btn-primary send-complain">Отправить</button>
            </div>
        </div>
    </div>
</div>