<div class="panel panel-default pane">
    <div class="panel-heading">
        <h3 class="panel-title">Объявления</h3>
    </div>
    <ul class="list-group">
        <?php if (!empty($this->ads)): ?>
            <?php foreach ($this->ads as $ad): ?>
                <li class="list-group-item">
                    <div class="row same-columns">
                        <div class="col-lg-3 ads-preview-border-right">
                            <?php $imgs = glob("./public/img/ads_imgs/{$ad['id']}_*");
                            if (!empty($imgs)) {
                                $src = $this->thumbHelper(
                                    basename(
                                        glob("./public/img/ads_imgs/{$ad['id']}_*")[0]
                                    ),
                                    180,
                                    90
                                );
                            } else {
                                $src = '/img/no-photo.png';
                            }
                            ?>
                            <img src="<?= $src ?>" alt="..." width="180px" height="90px">
                        </div>
                        <div class="col-lg-6 ads-preview-border-right">
                            <h4>
                                <a href="<?= $this->url('showAds', array('adsId' => $ad['id'])) ?>">
                                    <?= $this->escapeHtml($ad['title']) ?>
                                </a>
                            </h4>
                        </div>
                        <div class="col-lg-3">
                            <h4>
                                <?php if (!empty($ad['price'])): ?>
                                    <?= $this->escapeHtml($ad['price']) ?>
                                    <?= $ad['currencyid']['name'] ?>
                                <?php else: ?>
                                    Договорная
                                <?php endif; ?>
                            </h4>
                            <h5>
                                <?php if (!empty($ad['cityid'])): ?>
                                    <?= $this->escapeHtml($ad['cityid']['name']) ?>
                                <?php else: ?>
                                    Вся Украина
                                <?php endif; ?>
                            </h5>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        <?php else: ?>
            <?= $this->partial('ads/partial/ads-no-found') ?>
        <?php endif; ?>
    </ul>
</div>
