<?php $this->inlineScript()
    ->appendFile($this->basePath() . '/js/common/base/ads-block.js');?>

<div class="panel panel-default pane">
    <div class="panel-heading">
        <h3 class="panel-title">Объявления</h3>
    </div>
    <ul class="list-group">
        <?php if (!empty($this->ads)): ?>
            <?php foreach ($this->ads as $ad): ?>
                <li id="ads-<?= $ad['id'] ?>" class="list-group-item">
                    <div class="row same-columns">
                        <div class="col-lg-3 ads-preview-border-right">
                            <?php $imgs = glob("./public/img/ads_imgs/{$ad['id']}_*");
                            if (!empty($imgs)) {
                                $src = $this->thumbHelper(
                                    basename(
                                        glob("./public/img/ads_imgs/{$ad['id']}_*")[0]
                                    ),
                                    180,
                                    90
                                );
                            } else {
                                $src = '/img/no-photo.png';
                            }
                            ?>
                            <img src="<?= $src ?>" alt="..." width="180px" height="90px">
                        </div>
                        <div class="col-lg-6 ads-preview-border-right">
                            <h4 class="row-fluid">
                                <a href="<?= $this->url('showAds', array('adsId' => $ad['id'])) ?>">
                                    <?= $this->escapeHtml($ad['title']) ?>
                                </a>
                            </h4>

                            <div class="ads-date-created">
                                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                <?php
                                $datetime1 = new DateTime();
                                $datetime2 = $ad['created'];
                                $interval = $datetime1->diff($datetime2);
                                echo $interval->format('%a дней');
                                ?>
                            </div>

                            <?php $identity = $this->identity() ?>
                            <?php if (is_object($identity) &&
                                $identity->getId() === $ad['userid']['id']
                            ): ?>
                                <div class="row text-right">
                                    <div class="col-lg-8 col-lg-push-4">
                                        <a class="btn btn-default btn-xs"
                                           href="<?= $this->url('updateUserAds/getUpdateAdsForm', array('adsId' => $ad['id'])) ?>"
                                            >
                                            Обновить
                                        </a>
                                        <a class="btn btn-default btn-xs deleteAds"
                                           data-modal-body="Вы уверены, что хотите удальть объявление?"
                                           data-modal-title="Удаление объявления"
                                           data-notify-success="Объявление успешно удалено"
                                           href="<?= $this->url('deleteUserAds', array('adsId' => $ad['id'])) ?>">
                                            Удалить
                                        </a>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="col-lg-3">
                            <h4>
                                <?php if (!empty($ad['price'])): ?>
                                    <?= $this->escapeHtml($ad['price']) ?>
                                    <?= $ad['currencyid']['name'] ?>
                                <?php else: ?>
                                    Договорная
                                <?php endif; ?>
                            </h4>
                            <h5>
                                <?php if (!empty($ad['cityid'])): ?>
                                    <?= $this->escapeHtml($ad['cityid']['name']) ?>
                                <?php else: ?>
                                    Вся Украина
                                <?php endif; ?>
                            </h5>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        <?php else: ?>
            <?= $this->partial('ads/partial/ads-no-found') ?>
        <?php endif; ?>
    </ul>
</div>
